### ISSUE TITLE
Implement locking

### ISSUE THREAD

**Issue by laurensrouw** [laurensrouw/mod8-project#4]
Implement locking with named locks.

    lock name
    # critical_section
    unlock name

**Comment by Magnificus36** [comment]
Maybe it would also be nice if it would be possible to check who has the lock.
This could be done by allocating two memory addresses per lock. One for the locking and one in which the holder of the lock writes its SPID directly after acquiring the lock. When the lock is released this second address should also be cleared.

This can be used unsure that only the holder of the lock can unlock it.

**Comment by Magnificus36** [comment]
First implementation in e93803c60afd4f2e40738c8f3c1c833bce1533f8
