### ISSUE TITLE
Variable decleration needs to support global variables

### ISSUE THREAD

**Issue by laurensrouw** [laurensrouw/mod8-project#5]
The following code should write and read from global memory

    global int a = 0

**Comment by Magnificus36** [comment]
VarID need isGlobal flag which should be set by the Checker in the same way as the type is set.

**Comment by Magnificus36** [comment]
That commit should have referenced #4

**Comment by Magnificus36** [comment]
Currently the checker accepts local and global variables with the same name. This should not be possible since it would be to ambiguous.

**Comment by Magnificus36** [comment]
Works
